		ORG 0000H
		LJMP MAIN
		ORG 0040H
SHUZI 	EQU 00H
MAIN:	MOV B , #16
		MOV DPTR , #2000H
		MOV R1 , #00H
LOOP:	MOVX A , @DPTR
		XRL A , SHUZI
		CJNE A , #0 , TMP
		INC R1
TMP:	INC DPTR
		DJNZ B , LOOP
		MOV DPTR , #2010H
		MOV A , R1
		MOVX @DPTR , A
		SJMP $
		END
		